import { StyleSheet, Platform } from 'react-native';
import { theme } from '../../../src/constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.bg,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 20,
  },
  headerSubtitle: {
    fontSize: 14,
    color: theme.textMuted,
    fontWeight: '500',
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: theme.text,
    letterSpacing: -0.5,
  },
  headerIconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: theme.surface,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme.border,
  },
  monthSelectorContainer: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  monthSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: theme.surface,
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: theme.border,
  },
  monthArrow: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: theme.surfaceLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  monthInfo: {
    alignItems: 'center',
  },
  monthText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.text,
  },
  yearText: {
    fontSize: 12,
    color: theme.textMuted,
    fontWeight: '500',
  },
  subTabsWrapper: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  subTabsContainer: {
    flexDirection: 'row',
    backgroundColor: theme.surface,
    borderRadius: 14,
    padding: 6,
    borderWidth: 1,
    borderColor: theme.border,
    minWidth: '100%',
  },
  subTabItem: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: 'center',
    borderRadius: 10,
    minWidth: 80,
  },
  subTabItemActive: {
    backgroundColor: theme.surfaceLight,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  subTabText: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.textMuted,
  },
  subTabTextActive: {
    color: theme.text,
  },
  filtersContainer: {
    flexDirection: 'row',
    marginBottom: 16,
    gap: 10,
  },
  filterPill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: theme.surface,
    borderWidth: 1,
    borderColor: theme.border,
    gap: 6,
  },
  filterPillActive: {
    backgroundColor: theme.primaryOpacity,
    borderColor: theme.primary,
  },
  filterText: {
    color: theme.textMuted,
    fontSize: 12,
    fontWeight: '600',
  },
  filterTextActive: {
    color: theme.primary,
  },
  scrollContent: {
    paddingHorizontal: 20,
  },
  card: {
    backgroundColor: theme.surface,
    borderRadius: 24,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: theme.border,
    ...Platform.select({
      ios: {
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  cardTitle: {
    color: theme.text,
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: -0.3,
  },
  cardSubtitle: {
    color: theme.textMuted,
    fontSize: 12,
    marginTop: 2,
  },
  chartWrapper: {
    alignItems: 'center',
    marginHorizontal: -10,
  },
  lineChart: {
    borderRadius: 16,
  },
  // Donut
  donutWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  centerAll: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  donutHole: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: theme.surface,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme.border,
  },
  donutCenterText: {
    color: theme.text,
    fontSize: 16,
    fontWeight: 'bold',
  },
  donutCenterSubtext: {
    color: theme.textMuted,
    fontSize: 10,
    marginTop: 2,
  },
  customLegendContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: 24,
    gap: 12,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.surfaceLight,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    maxWidth: '45%',
  },
  legendColor: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 8,
  },
  legendText: {
    color: theme.textMuted,
    fontSize: 11,
  },
  legendValue: {
    color: theme.text,
    fontWeight: 'bold',
  },
  // Ranking
  rankingItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
    gap: 12,
  },
  rankingIconContainer: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryIconBg: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rankingHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  rankingLabel: {
    color: theme.text,
    fontSize: 14,
    fontWeight: '600',
  },
  rankingValue: {
    color: theme.text,
    fontSize: 13,
    fontWeight: '500',
  },
  progressBarBg: {
    height: 6,
    backgroundColor: theme.border,
    borderRadius: 3,
    width: '100%',
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 3,
  },
  // Summary Grid
  summaryGrid: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  summarySmallCard: {
    flex: 1,
    backgroundColor: theme.surface,
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.border,
  },
  summaryIconBg: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  summaryLabel: {
    color: theme.textMuted,
    fontSize: 12,
    fontWeight: '500',
    marginBottom: 4,
  },
  summaryValue: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  summaryDailyAvg: {
    fontSize: 11,
    color: theme.textMuted,
    marginBottom: 8,
  },
  comparisonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  comparisonText: {
    fontSize: 10,
    fontWeight: '600',
  },
  // Total Tab Card
  totalTabCard: {
    backgroundColor: theme.surface,
    borderRadius: 24,
    padding: 18,
    marginBottom: 24,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
  },
  totalTabIconBg: {
    width: 56,
    height: 56,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  totalTabLabel: {
    color: theme.textMuted,
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 4,
  },
  totalTabValue: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 2,
  },
  totalTabSubValue: {
    fontSize: 13,
    color: theme.textMuted,
  },
  // Empty State
  emptyStateContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  emptyStateIconBg: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: theme.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: theme.border,
  },
  emptyStateTitle: {
    color: theme.text,
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  emptyStateSubtitle: {
    color: theme.textMuted,
    fontSize: 14,
    textAlign: 'center',
    paddingHorizontal: 40,
  },
  // Insights
  insightsContainer: {
    marginBottom: 24,
  },
  insightsTitle: {
    color: theme.text,
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 16,
    letterSpacing: -0.3,
  },
  insightRow: {
    flexDirection: 'row',
    gap: 12,
  },
  insightCard: {
    flex: 1,
    backgroundColor: theme.surface,
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.border,
  },
  insightIconBg: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  insightLabel: {
    color: theme.textMuted,
    fontSize: 11,
    fontWeight: '600',
    marginBottom: 4,
  },
  insightValue: {
    color: theme.text,
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 2,
  },
  insightSubValue: {
    color: theme.textMuted,
    fontSize: 10,
  },
  // Tips
  tipsCard: {
    backgroundColor: theme.surfaceLight,
    borderRadius: 20,
    padding: 16,
    marginBottom: 30,
    borderLeftWidth: 4,
    borderLeftColor: theme.warning,
  },
  tipsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  tipsTitle: {
    color: theme.text,
    fontSize: 14,
    fontWeight: 'bold',
  },
  tipsContent: {
    color: theme.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
});
